### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by daviss57** [jasonmadigan/ha-hkc#23]
Hi Jason, 

Seems to be an issue with the update. 

Logger: homeassistant.setup
Source: setup.py:269
First occurred: 13:19:45 (1 occurrences)
Last logged: 13:19:45

Setup failed for custom integration 'hkc_alarm': Requirements for hkc_alarm not found: ['pyhkc==0.4.4'].

**Comment by jasonmadigan** [comment]
Should be fixed by https://github.com/jasonmadigan/ha-hkc/releases/tag/1.0.15

**Comment by daviss57** [comment]
Still seems to be an issue.

Logger: homeassistant.setup
Source: setup.py:269
First occurred: 16:19:03 (1 occurrences)
Last logged: 16:19:03

Setup failed for custom integration 'hkc_alarm': Requirements for hkc_alarm not found: ['pyhkc==0.4.7'].

**Comment by daviss57** [comment]
Still an issue today. Reverting to 1.0.07

2024-06-27 12:30:50.686 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package pyhkc==0.4.7: ERROR: Cannot install pyhkc==0.4.7 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2024-06-27 12:30:50.749 WARNING (MainThread) [deebot_client.message] Could not parse getCleanInfo: {'code': 20003, 'msg': 'rcp not support'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/deebot_client/message.py", line 63, in wrapper
    if response.state == HandlingState.ANALYSE:
       ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'state'
